#spring.jpa.hibernate.ddl-auto= create-drop
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/band?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.initialization-mode=always
#spring.datasource.data=classpath:data.sql
#spring.jpa.show-sql=true

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: a1ff5576a815be
    password: 74807eba439521
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/band?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true


logging:
  level:
    hibernate:
      type: trace








#auth0.issuer:https://dertoaster.eu.auth0.com/
#auth0.apiAudience:https://localhost:8080

