insert into role (name) value ('USER')
insert into role (name) value ('ADMIN')
insert into user (name, email, username, enabled, password) values ('Ashkan', 'blabla@blalba.de', 'derToaster1412', true, '$2y$12$WzEwRSwWSVCP3.LRWUvQAOMDoAKBzJ7rBPSdEMRjCa6kwt.29/bKu')
insert into user (name, email, username, enabled, password) values ('Jasmin', 'yadeyade@blalba.de', 'Zockerlady', true, 'yadeyade')
insert into user (name, email, username, enabled, password) values ('User', 'yadeyade@blalba.de', 'user', true, '$2y$12$MlPwR/nF9ixmD1P3x.ZJNOwBIWIW.xX6ZSLPbmBmzJsD2T6WQjkaa')
insert into user (name, email, username, enabled, password) values ('Admin', 'yadeyade@blalba.de', 'admin', true, '$2y$12$3GCrY8KRT.zNT9TIBWPjsuf6ieKh8btST0Ytl9TBa5zXCMVBsqlpC')
insert into user (name, email, username, enabled, password) values ('secondAdmin', 'yadeyade@blalba.de', 'secondAdmin', true, '$2y$12$3GCrY8KRT.zNT9TIBWPjsuf6ieKh8btST0Ytl9TBa5zXCMVBsqlpC')
insert into user_role (user_id, role_id) value (3,1)
insert into user_role (user_id, role_id) value (4,2)
insert into user_role (user_id, role_id) value (5,2)
insert into skilllevels(skilllevel) values('Noob')
insert into skilllevels(skilllevel) values('Intermediate')
insert into skilllevels(skilllevel) values('Advanced')
insert into skilllevels(skilllevel) values('Pro')
insert into skilllevels(skilllevel) values('Godlike')
insert into skilllevels(skilllevel) values('M M M M M Multikill')
insert into skilllevels(skilllevel) values('Hendrix')
insert into instruments(name) values('Guitar')
insert into instruments(name) values('Flute')
insert into instruments(name) values('Drums')
insert into instruments(name) values('Keys')
insert into instruments(name) values('Vocal')
insert into instruments(name) values('Alto Sax')
insert into instruments(name) values('Tenor Sax')
insert into instruments(name) values('Soprano Sax')
insert into instruments(name) values('Trompet')
insert into instruments(name) values('Bass')
insert into instruments(name) values('Doublebass')
insert into instruments(name) values('Percussions')
insert into instruments(name) values('Banjo')
insert into instruments(name) values('Mouthorgan')
insert into instruments(name) values('Clarinet')
insert into instruments(name) values('Tuba')
insert into instruments(name) values('Trombone')
insert into skills(user_id, instrument_id, skilllevel_id) values(1, 1, 1)

